"""Update employment table

Revision ID: 766799ad114e
Revises: 26b05faa8ea3
Create Date: 2025-05-30 02:31:51.286937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766799ad114e'
down_revision: Union[str, None] = '26b05faa8ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employments', sa.Column('from_date', sa.Date(), nullable=False))
    op.add_column('employments', sa.Column('to_date', sa.Date(), nullable=True))
    op.drop_column('employments', 'to_year')
    op.drop_column('employments', 'from_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employments', sa.Column('from_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employments', sa.Column('to_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('employments', 'to_date')
    op.drop_column('employments', 'from_date')
    # ### end Alembic commands ###
