"""Create employment,kyc,asset,income,liability,wealtgsource tables

Revision ID: 88f941574fdb
Revises: 3def9d45dd50
Create Date: 2025-05-23 02:39:16.005855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f941574fdb'
down_revision: Union[str, None] = '3def9d45dd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_experience', sa.Enum('less_than_5', 'between_5_10', 'more_than_10', name='experiencelevel'), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('low', 'medium', 'high', name='risktolerance'), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_wealth_source', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_worth', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_kyc_id'), 'kyc', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('bond', 'liquidity', 'real_estate', 'others', name='assettype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('employments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('from_year', sa.Integer(), nullable=False),
    sa.Column('to_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employments_id'), 'employments', ['id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=False),
    sa.Column('income_type', sa.Enum('salary', 'investment', 'others', name='incometype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=False),
    sa.Column('liability_type', sa.Enum('personal_loan', 'real_estate_loan', 'others', name='liabilitytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liabilities_id'), 'liabilities', ['id'], unique=False)
    op.create_table('wealth_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('inheritance', 'donation', name='wealthsourcetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wealth_sources_id'), 'wealth_sources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wealth_sources_id'), table_name='wealth_sources')
    op.drop_table('wealth_sources')
    op.drop_index(op.f('ix_liabilities_id'), table_name='liabilities')
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_employments_id'), table_name='employments')
    op.drop_table('employments')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_kyc_id'), table_name='kyc')
    op.drop_table('kyc')
    # ### end Alembic commands ###
