"""Update KYC model 1

Revision ID: cf6d9afc82d8
Revises: d530c6c9d8b5
Create Date: 2025-06-12 17:26:30.594383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6d9afc82d8'
down_revision: Union[str, None] = 'd530c6c9d8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc', 'market_experience',
               existing_type=postgresql.ENUM('less_than_5', 'between_5_10', 'more_than_10', name='experiencelevel'),
               nullable=True)
    op.alter_column('kyc', 'risk_tolerance',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='risktolerance'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc', 'risk_tolerance',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='risktolerance'),
               nullable=False)
    op.alter_column('kyc', 'market_experience',
               existing_type=postgresql.ENUM('less_than_5', 'between_5_10', 'more_than_10', name='experiencelevel'),
               nullable=False)
    # ### end Alembic commands ###
