"""Update KYC model

Revision ID: d530c6c9d8b5
Revises: 766799ad114e
Create Date: 2025-06-12 17:25:32.836739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd530c6c9d8b5'
down_revision: Union[str, None] = '766799ad114e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'currency')
    op.drop_column('incomes', 'currency')
    op.drop_column('kyc', 'net_worth')
    op.drop_column('kyc', 'total_wealth_source')
    op.drop_column('kyc', 'total_liabilities')
    op.drop_column('kyc', 'total_assets')
    op.drop_column('kyc', 'total_income')
    op.drop_column('liabilities', 'currency')
    op.drop_column('wealth_sources', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wealth_sources', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('liabilities', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kyc', sa.Column('total_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('kyc', sa.Column('total_assets', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('kyc', sa.Column('total_liabilities', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('kyc', sa.Column('total_wealth_source', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('kyc', sa.Column('net_worth', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('incomes', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
